kind: pipeline
type: kubernetes
name: Release

steps:
  - name: release on codeberg
    image: golang:1.24.3
    environment:
      CODEBERG_URL: https://codeberg.org/api/v1/repos/simon-kolkmann/gowt/releases
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - apt update && apt install -y jq

      - ./scripts/build.sh
      - ./scripts/publish.sh

trigger:
  event:
    - tag
