package types

type Mutation int

const (
	MUTATION_ACTIVE_ENTRY Mutation = iota
	MUTATION_ENTRIES
	MUTATION_INIT
	MUTATION_LANGUAGE
	MUTATION_SETTINGS_DAILY_SETUP_TIME
	MUTATION_SETTINGS_HOURS_PER_DAY
)
