services:
  gowt:
    build:
      context: .
    container_name: gowt
    working_dir: /app/gowt
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      TERM: xterm-256color
    volumes:
      - $HOME/.ssh:/root/.ssh:ro
      - $PWD:/app/gowt
