services:
  gowt:
    image: golang:1.24.0
    container_name: gowt
    working_dir: /app/gowt
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      TERM: xterm-256color
    volumes:
      - $PWD:/app/gowt
